// Generated by gencpp from file agvcode/AgvNav.msg
// DO NOT EDIT!


#ifndef AGVCODE_MESSAGE_AGVNAV_H
#define AGVCODE_MESSAGE_AGVNAV_H

#include <ros/service_traits.h>


#include <agvcode/AgvNavRequest.h>
#include <agvcode/AgvNavResponse.h>


namespace agvcode
{

struct AgvNav
{

typedef AgvNavRequest Request;
typedef AgvNavResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AgvNav
} // namespace agvcode


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agvcode::AgvNav > {
  static const char* value()
  {
    return "d314b4d308820390a64698753b2ba3b9";
  }

  static const char* value(const ::agvcode::AgvNav&) { return value(); }
};

template<>
struct DataType< ::agvcode::AgvNav > {
  static const char* value()
  {
    return "agvcode/AgvNav";
  }

  static const char* value(const ::agvcode::AgvNav&) { return value(); }
};


// service_traits::MD5Sum< ::agvcode::AgvNavRequest> should match 
// service_traits::MD5Sum< ::agvcode::AgvNav > 
template<>
struct MD5Sum< ::agvcode::AgvNavRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agvcode::AgvNav >::value();
  }
  static const char* value(const ::agvcode::AgvNavRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agvcode::AgvNavRequest> should match 
// service_traits::DataType< ::agvcode::AgvNav > 
template<>
struct DataType< ::agvcode::AgvNavRequest>
{
  static const char* value()
  {
    return DataType< ::agvcode::AgvNav >::value();
  }
  static const char* value(const ::agvcode::AgvNavRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agvcode::AgvNavResponse> should match 
// service_traits::MD5Sum< ::agvcode::AgvNav > 
template<>
struct MD5Sum< ::agvcode::AgvNavResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agvcode::AgvNav >::value();
  }
  static const char* value(const ::agvcode::AgvNavResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agvcode::AgvNavResponse> should match 
// service_traits::DataType< ::agvcode::AgvNav > 
template<>
struct DataType< ::agvcode::AgvNavResponse>
{
  static const char* value()
  {
    return DataType< ::agvcode::AgvNav >::value();
  }
  static const char* value(const ::agvcode::AgvNavResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGVCODE_MESSAGE_AGVNAV_H
