// Generated by gencpp from file agvcode/WordCount.msg
// DO NOT EDIT!


#ifndef AGVCODE_MESSAGE_WORDCOUNT_H
#define AGVCODE_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <agvcode/WordCountRequest.h>
#include <agvcode/WordCountResponse.h>


namespace agvcode
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace agvcode


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agvcode::WordCount > {
  static const char* value()
  {
    return "a9a24dbc1cac26f2f8c73d77906b969c";
  }

  static const char* value(const ::agvcode::WordCount&) { return value(); }
};

template<>
struct DataType< ::agvcode::WordCount > {
  static const char* value()
  {
    return "agvcode/WordCount";
  }

  static const char* value(const ::agvcode::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::agvcode::WordCountRequest> should match 
// service_traits::MD5Sum< ::agvcode::WordCount > 
template<>
struct MD5Sum< ::agvcode::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agvcode::WordCount >::value();
  }
  static const char* value(const ::agvcode::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agvcode::WordCountRequest> should match 
// service_traits::DataType< ::agvcode::WordCount > 
template<>
struct DataType< ::agvcode::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::agvcode::WordCount >::value();
  }
  static const char* value(const ::agvcode::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agvcode::WordCountResponse> should match 
// service_traits::MD5Sum< ::agvcode::WordCount > 
template<>
struct MD5Sum< ::agvcode::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agvcode::WordCount >::value();
  }
  static const char* value(const ::agvcode::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agvcode::WordCountResponse> should match 
// service_traits::DataType< ::agvcode::WordCount > 
template<>
struct DataType< ::agvcode::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::agvcode::WordCount >::value();
  }
  static const char* value(const ::agvcode::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGVCODE_MESSAGE_WORDCOUNT_H
