// Generated by gencpp from file agvworkspace/AgvNavResponse.msg
// DO NOT EDIT!


#ifndef AGVWORKSPACE_MESSAGE_AGVNAVRESPONSE_H
#define AGVWORKSPACE_MESSAGE_AGVNAVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agvworkspace
{
template <class ContainerAllocator>
struct AgvNavResponse_
{
  typedef AgvNavResponse_<ContainerAllocator> Type;

  AgvNavResponse_()
    : status(false)
    , error_msg()  {
    }
  AgvNavResponse_(const ContainerAllocator& _alloc)
    : status(false)
    , error_msg(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_msg_type;
  _error_msg_type error_msg;





  typedef boost::shared_ptr< ::agvworkspace::AgvNavResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agvworkspace::AgvNavResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AgvNavResponse_

typedef ::agvworkspace::AgvNavResponse_<std::allocator<void> > AgvNavResponse;

typedef boost::shared_ptr< ::agvworkspace::AgvNavResponse > AgvNavResponsePtr;
typedef boost::shared_ptr< ::agvworkspace::AgvNavResponse const> AgvNavResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agvworkspace::AgvNavResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agvworkspace::AgvNavResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace agvworkspace

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::agvworkspace::AgvNavResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agvworkspace::AgvNavResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agvworkspace::AgvNavResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agvworkspace::AgvNavResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agvworkspace::AgvNavResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agvworkspace::AgvNavResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agvworkspace::AgvNavResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "426bb48ea6b00ad5853fdaddd836bcc6";
  }

  static const char* value(const ::agvworkspace::AgvNavResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x426bb48ea6b00ad5ULL;
  static const uint64_t static_value2 = 0x853fdaddd836bcc6ULL;
};

template<class ContainerAllocator>
struct DataType< ::agvworkspace::AgvNavResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agvworkspace/AgvNavResponse";
  }

  static const char* value(const ::agvworkspace::AgvNavResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agvworkspace::AgvNavResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n\
string error_msg\n\
\n\
\n\
";
  }

  static const char* value(const ::agvworkspace::AgvNavResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agvworkspace::AgvNavResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.error_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AgvNavResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agvworkspace::AgvNavResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agvworkspace::AgvNavResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "error_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGVWORKSPACE_MESSAGE_AGVNAVRESPONSE_H
