// Generated by gencpp from file agvworkspace/AgvNav.msg
// DO NOT EDIT!


#ifndef AGVWORKSPACE_MESSAGE_AGVNAV_H
#define AGVWORKSPACE_MESSAGE_AGVNAV_H

#include <ros/service_traits.h>


#include <agvworkspace/AgvNavRequest.h>
#include <agvworkspace/AgvNavResponse.h>


namespace agvworkspace
{

struct AgvNav
{

typedef AgvNavRequest Request;
typedef AgvNavResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AgvNav
} // namespace agvworkspace


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agvworkspace::AgvNav > {
  static const char* value()
  {
    return "d314b4d308820390a64698753b2ba3b9";
  }

  static const char* value(const ::agvworkspace::AgvNav&) { return value(); }
};

template<>
struct DataType< ::agvworkspace::AgvNav > {
  static const char* value()
  {
    return "agvworkspace/AgvNav";
  }

  static const char* value(const ::agvworkspace::AgvNav&) { return value(); }
};


// service_traits::MD5Sum< ::agvworkspace::AgvNavRequest> should match 
// service_traits::MD5Sum< ::agvworkspace::AgvNav > 
template<>
struct MD5Sum< ::agvworkspace::AgvNavRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agvworkspace::AgvNav >::value();
  }
  static const char* value(const ::agvworkspace::AgvNavRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agvworkspace::AgvNavRequest> should match 
// service_traits::DataType< ::agvworkspace::AgvNav > 
template<>
struct DataType< ::agvworkspace::AgvNavRequest>
{
  static const char* value()
  {
    return DataType< ::agvworkspace::AgvNav >::value();
  }
  static const char* value(const ::agvworkspace::AgvNavRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agvworkspace::AgvNavResponse> should match 
// service_traits::MD5Sum< ::agvworkspace::AgvNav > 
template<>
struct MD5Sum< ::agvworkspace::AgvNavResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agvworkspace::AgvNav >::value();
  }
  static const char* value(const ::agvworkspace::AgvNavResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agvworkspace::AgvNavResponse> should match 
// service_traits::DataType< ::agvworkspace::AgvNav > 
template<>
struct DataType< ::agvworkspace::AgvNavResponse>
{
  static const char* value()
  {
    return DataType< ::agvworkspace::AgvNav >::value();
  }
  static const char* value(const ::agvworkspace::AgvNavResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGVWORKSPACE_MESSAGE_AGVNAV_H
