// Generated by gencpp from file agvworkspace/WordCount.msg
// DO NOT EDIT!


#ifndef AGVWORKSPACE_MESSAGE_WORDCOUNT_H
#define AGVWORKSPACE_MESSAGE_WORDCOUNT_H

#include <ros/service_traits.h>


#include <agvworkspace/WordCountRequest.h>
#include <agvworkspace/WordCountResponse.h>


namespace agvworkspace
{

struct WordCount
{

typedef WordCountRequest Request;
typedef WordCountResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WordCount
} // namespace agvworkspace


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::agvworkspace::WordCount > {
  static const char* value()
  {
    return "a9a24dbc1cac26f2f8c73d77906b969c";
  }

  static const char* value(const ::agvworkspace::WordCount&) { return value(); }
};

template<>
struct DataType< ::agvworkspace::WordCount > {
  static const char* value()
  {
    return "agvworkspace/WordCount";
  }

  static const char* value(const ::agvworkspace::WordCount&) { return value(); }
};


// service_traits::MD5Sum< ::agvworkspace::WordCountRequest> should match 
// service_traits::MD5Sum< ::agvworkspace::WordCount > 
template<>
struct MD5Sum< ::agvworkspace::WordCountRequest>
{
  static const char* value()
  {
    return MD5Sum< ::agvworkspace::WordCount >::value();
  }
  static const char* value(const ::agvworkspace::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::agvworkspace::WordCountRequest> should match 
// service_traits::DataType< ::agvworkspace::WordCount > 
template<>
struct DataType< ::agvworkspace::WordCountRequest>
{
  static const char* value()
  {
    return DataType< ::agvworkspace::WordCount >::value();
  }
  static const char* value(const ::agvworkspace::WordCountRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::agvworkspace::WordCountResponse> should match 
// service_traits::MD5Sum< ::agvworkspace::WordCount > 
template<>
struct MD5Sum< ::agvworkspace::WordCountResponse>
{
  static const char* value()
  {
    return MD5Sum< ::agvworkspace::WordCount >::value();
  }
  static const char* value(const ::agvworkspace::WordCountResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::agvworkspace::WordCountResponse> should match 
// service_traits::DataType< ::agvworkspace::WordCount > 
template<>
struct DataType< ::agvworkspace::WordCountResponse>
{
  static const char* value()
  {
    return DataType< ::agvworkspace::WordCount >::value();
  }
  static const char* value(const ::agvworkspace::WordCountResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AGVWORKSPACE_MESSAGE_WORDCOUNT_H
