// Generated by gencpp from file agvworkspace/WordCountRequest.msg
// DO NOT EDIT!


#ifndef AGVWORKSPACE_MESSAGE_WORDCOUNTREQUEST_H
#define AGVWORKSPACE_MESSAGE_WORDCOUNTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agvworkspace
{
template <class ContainerAllocator>
struct WordCountRequest_
{
  typedef WordCountRequest_<ContainerAllocator> Type;

  WordCountRequest_()
    : words(0.0)  {
    }
  WordCountRequest_(const ContainerAllocator& _alloc)
    : words(0.0)  {
  (void)_alloc;
    }



   typedef float _words_type;
  _words_type words;





  typedef boost::shared_ptr< ::agvworkspace::WordCountRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agvworkspace::WordCountRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WordCountRequest_

typedef ::agvworkspace::WordCountRequest_<std::allocator<void> > WordCountRequest;

typedef boost::shared_ptr< ::agvworkspace::WordCountRequest > WordCountRequestPtr;
typedef boost::shared_ptr< ::agvworkspace::WordCountRequest const> WordCountRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agvworkspace::WordCountRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agvworkspace::WordCountRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace agvworkspace

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::agvworkspace::WordCountRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agvworkspace::WordCountRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agvworkspace::WordCountRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agvworkspace::WordCountRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agvworkspace::WordCountRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agvworkspace::WordCountRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agvworkspace::WordCountRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d44201b6004f1d09d55427603c7047c3";
  }

  static const char* value(const ::agvworkspace::WordCountRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd44201b6004f1d09ULL;
  static const uint64_t static_value2 = 0xd55427603c7047c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::agvworkspace::WordCountRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agvworkspace/WordCountRequest";
  }

  static const char* value(const ::agvworkspace::WordCountRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agvworkspace::WordCountRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 words\n\
";
  }

  static const char* value(const ::agvworkspace::WordCountRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agvworkspace::WordCountRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.words);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WordCountRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agvworkspace::WordCountRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agvworkspace::WordCountRequest_<ContainerAllocator>& v)
  {
    s << indent << "words: ";
    Printer<float>::stream(s, indent + "  ", v.words);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGVWORKSPACE_MESSAGE_WORDCOUNTREQUEST_H
